# The numpy-random Package

The purpose of this assignment is to explore and investigate the numpy.random package and its use in Python Data Analysis. The assignment is broken down into 4 separate tasks in the notebook. They are:

* Explain the overall purpose of the package
* Explain the use of the "Simple random data" and "Permutations" functions
* Explain the use and purpose of at least five " Distributions" functions
* Explain the use of seeds in generatinf pseudorandom numbers

### Section 1 Explain the overall purpose of the package

**Numpy** is a library for conducting numerical computing in Python. Numpy is a portmanteau formed from **Num**-eric and **py**-thon. The library contains numerous features that are of great utility in data analysis/science. Examples of these are:

* Data structures
* Algorithms
* Ability to carry out task such as indexing, slicing and iterating 

Numpy and pandas are the two most important packages we interact with when working with datasets.

The numpy.random module allows us to generate many quantities(a few integers to massive amounts of random items) and types such as floats, integers and even strings.

We can use the generated objects to validate ML models, 



### Section 2 Explain the use of the "Simple random data" and "Permutations" functions

We start numpy by importing it as np. We will generate some simple random data. We will explore random arrays, calling different random functions and the different items that can be contained within an arrray in the random package. The random package is called by using ```np.random.rand()``` command

In [15]:
import numpy as np
np.random.rand(4)

array([0.07852397, 0.68408153, 0.63839786, 0.49912646])

In [20]:
#We can shape the data in the random array also, here it will  return a 4 x4 array

x = np.random.rand(4,4)
x

array([[0.0515464 , 0.85481067, 0.91528064, 0.86311129],
       [0.3313748 , 0.89200419, 0.34739065, 0.27564913],
       [0.99183479, 0.54923049, 0.55215905, 0.94536101],
       [0.52477843, 0.02299857, 0.76492848, 0.4858573 ]])

In [21]:
#We can then manipulate this data:
x * 10

array([[0.51546395, 8.54810669, 9.15280644, 8.63111285],
       [3.31374799, 8.92004192, 3.47390646, 2.75649129],
       [9.91834794, 5.49230489, 5.52159047, 9.45361006],
       [5.24778426, 0.22998568, 7.64928481, 4.85857297]])

In [43]:
#Let's say we want some intergers (generate 6 ints between 0 and 15 (not including 15))
y = np.random.randint(0, 15, 6)
y

array([11, 14,  3,  3,  2, 10])

In [44]:
#We can even use the random module to make a choice for us
np.random.choice(10,4)



array([2, 4, 2, 6])

In [61]:
#We can do the same for non numbers, returns a random choice with the datatype a unicode 5 character string
gMit = ['Tom', 'Brian', 'Ian']
np.random.choice(gMit,1)

array(['Brian'], dtype='<U5')

### Section 3 Explain the use and purpose of at least five <strong>"Distributions"</strong> functions

### Section 4 Explain the use of seeds in generating pseudorandom numbers