# The numpy-random Package

The purpose of this assignment is to explore and investigate the numpy.random package and its use in Python Data Analysis. The assignment is broken down into 4 separate tasks in the notebook. They are:

* Explain the overall purpose of the package
* Explain the use of the "Simple random data" and "Permutations" functions
* Explain the use and purpose of at least five " Distributions" functions
* Explain the use of seeds in generatinf pseudorandom numbers

### Section 1 Explain the overall purpose of the package

**Numpy** is a library for conducting numerical computing in Python. Numpy is a portmanteau formed from **Num**-eric and **py**-thon. The library contains numerous features that are of great utility in data analysis/science. Examples of these are:

* Data structures
* Algorithms
* Ability to carry out task such as indexing, slicing and iterating 

Numpy and pandas are the two most important packages we interact with when working with datasets.

The numpy.random module allows us to generate many quantities(a few integers to massive amounts of random items) and types such as floats, integers and even strings.

We can use the generated objects to validate ML models, 



### Section 2 Explain the use of the "Simple random data" and "Permutations" functions

We start numpy by importing it as np. We will generate some simple random data. We will explore random arrays, calling different random functions and the different items that can be contained within an arrray in the random package. The random package is called by using ```np.random.rand()``` command

In [2]:
import numpy as np


In [3]:
#We can generate a simple array (1 dimensional array) with randon numbers with 4 items by calling:
np.random.rand(4)

array([0.91953935, 0.20076489, 0.21917826, 0.54839603])

In [4]:
#We can then generate more complex (2 dimensional array) arrays with randon numbers. Here are creating 2 x 2 shaped dataset.
np.random.rand(2,2)

array([[0.79820037, 0.40641133],
       [0.04105629, 0.57220709]])

In [5]:
#Here we are creating a 3 dimensional array.

x = np.random.rand(3,4,4)
x

array([[[0.37121191, 0.17049188, 0.65514261, 0.40013943],
        [0.71978632, 0.14978651, 0.20518072, 0.24889153],
        [0.17867966, 0.24990769, 0.41606128, 0.39532983],
        [0.57872799, 0.87773276, 0.44706938, 0.73624547]],

       [[0.20346322, 0.8762181 , 0.22584857, 0.37772105],
        [0.83325346, 0.48398715, 0.81769851, 0.87554388],
        [0.09003462, 0.2243844 , 0.12055484, 0.25594349],
        [0.19271606, 0.9417853 , 0.36634756, 0.42293081]],

       [[0.9385306 , 0.15564434, 0.24569986, 0.22369527],
        [0.02400594, 0.59514895, 0.81224101, 0.62704157],
        [0.56599521, 0.9960042 , 0.7968472 , 0.76541815],
        [0.30454742, 0.06250304, 0.34260361, 0.9137544 ]]])

In [6]:
#We can then manipulate this data by interacting with output by its assigned variable, in this case x:
x * 10

array([[[3.71211908, 1.70491877, 6.55142606, 4.00139427],
        [7.19786316, 1.49786506, 2.05180724, 2.48891527],
        [1.78679658, 2.49907691, 4.1606128 , 3.95329828],
        [5.78727986, 8.77732765, 4.4706938 , 7.3624547 ]],

       [[2.03463218, 8.76218105, 2.25848566, 3.77721047],
        [8.33253461, 4.83987153, 8.17698507, 8.75543884],
        [0.90034619, 2.24384404, 1.20554842, 2.55943492],
        [1.92716058, 9.41785303, 3.66347561, 4.22930809]],

       [[9.38530599, 1.55644341, 2.45699859, 2.23695271],
        [0.24005943, 5.95148948, 8.12241012, 6.27041567],
        [5.65995208, 9.96004204, 7.96847197, 7.65418147],
        [3.04547417, 0.62503038, 3.42603609, 9.13754405]]])

In [7]:
#Let's say we want some intergers (generate 6 ints between 0 and 15 (not including 15)). Here we are using the ```randint``` 
#or random interger function to create the ints.
y = np.random.randint(0, 15, 6)
y

array([10,  2,  8,  6,  9,  3])

In [8]:
#We can even use the random module to make a choice for us, here it will give us an output of 4 number between 0 and 10.
np.random.choice(10,4)

array([6, 0, 1, 7])

In [9]:
#We can do the same for non numbers, returns a random choice with the datatype a unicode 5 character string
gMit = ['Tom', 'Brian', 'Ian']
np.random.choice(gMit,1)

array(['Tom'], dtype='<U5')

### Permutations
The permutations functions deals with items are ordered when calling the function. There seems to be two functions teh shuffle function and permutations function.

The Permutation function takes an array 

In [25]:
np.random.permutation(20)


array([15,  7, 10,  1,  9, 19,  3, 13, 11,  6,  0, 16, 18,  8,  4,  2,  5,
       12, 17, 14])

In [22]:
#Shuffle
arr = np.arange(20)
np.random.shuffle(arr)
arr


array([17,  9,  6,  8, 18,  2, 11,  5,  7,  0, 14,  3,  4,  1, 16, 15, 12,
       19, 13, 10])

### Section 3 Explain the use and purpose of at least five <strong>"Distributions"</strong> functions

### Section 4 Explain the use of seeds in generating pseudorandom numbers